# Generated by Django 3.0.3 on 2020-02-27 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('avatar', models.TextField()),
                ('str_multi', models.FloatField()),
                ('wis_multi', models.FloatField()),
                ('lck_multi', models.FloatField()),
                ('tgh_multi', models.FloatField()),
                ('hp_tgh_multi', models.FloatField(default=12.5)),
                ('hp_lvl_diff', models.FloatField(default=-1)),
                ('def_stat', models.CharField(max_length=20)),
                ('dmg_stat', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('gold', models.IntegerField(default=10)),
                ('premium_curr', models.IntegerField(default=10)),
                ('max_hp', models.FloatField(default=100)),
                ('current_hp', models.FloatField(default=100)),
                ('level', models.IntegerField(default=1)),
                ('exp', models.FloatField(default=0)),
                ('total_exp', models.FloatField(default=0)),
                ('stamina', models.IntegerField(default=20)),
                ('strength', models.IntegerField(default=10)),
                ('wisdom', models.IntegerField(default=10)),
                ('luck', models.IntegerField(default=10)),
                ('toughness', models.IntegerField(default=10)),
                ('total_damage', models.FloatField(default=7.5)),
                ('defense', models.FloatField(default=2.5)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profession')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
