# Generated by Django 3.0.3 on 2020-02-27 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='lck_multi',
            field=models.FloatField(default=2.4),
        ),
        migrations.AlterField(
            model_name='profession',
            name='tgh_multi',
            field=models.FloatField(default=2.3),
        ),
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.ForeignKey(choices=[('1', 'Warrior'), ('2', 'Sorcerer')], on_delete=django.db.models.deletion.CASCADE, to='users.Profession'),
        ),
    ]
