# Generated by Django 3.0.3 on 2020-02-28 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200227_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profession',
            old_name='lck_multi',
            new_name='luck',
        ),
        migrations.RenameField(
            model_name='profession',
            old_name='str_multi',
            new_name='strength',
        ),
        migrations.RenameField(
            model_name='profession',
            old_name='tgh_multi',
            new_name='toughness',
        ),
        migrations.RenameField(
            model_name='profession',
            old_name='wis_multi',
            new_name='wisdom',
        ),
    ]
